controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    zebra_zero:
      type: position_controllers/JointGroupPositionController
    
    zerog_controller:
      type: zebra_zero/RobotController
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController
    
    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

zebra_zero:
  ros__parameters:
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint

    command_interfaces:
      - position

    state_interfaces:
      - position

velocity_controller:
  ros__parameters:
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity

trajectory_controller:
  ros__parameters:
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint
    
    command_interfaces:
      - position

    state_interfaces:
      - position
    
    allow_nonzero_velocity_at_trajectory_end: false

    # error tolerance during motion and at goal
    #constraints:
    #  first_joint: { trajectory: 0.01, goal: 0.005 }
    #  second_joint: { trajectory: 0.01, goal: 0.005 }
    #  third_joint: { trajectory: 0.01, goal: 0.005 }
    #  fourth_joint: { trajectory: 0.01, goal: 0.005 }
    #  fifth_joint: { trajectory: 0.01, goal: 0.005 }
    # sixth_joint: { trajectory: 0.01, goal: 0.005 }

    gains: # Required because we're controlling a velocity interface
      first_joint: {p: 1.0,  d: 0.0, i: 0.0, ff_velocity_scale: 0.1}
      second_joint: {p: 1.0,  d: 0.0, i: 0.0, ff_velocity_scale: 0.1}
      third_joint: {p: 1.0,  d: 0.0, i: 0.0, ff_velocity_scale: 0.1}
      fourth_joint: {p: 1.0,  d: 0.0, i: 0.0, ff_velocity_scale: 0.1}
      fifth_joint: {p: 1.0,  d: 0.0, i: 0.0, ff_velocity_scale: 0.1}
      sixth_joint: {p: 1.0,  d: 0.0, i: 0.0, ff_velocity_scale: 0.1}

zerog_controller:
  ros__parameters:
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint
    
    command_interfaces:
      - effort

    state_interfaces:
      - position

cartesian_motion_controller:
  ros__parameters:
    # TODO: make this better
    robot_description: "/home/bburns/ros2/install/zebra_zero/share/zebra_zero/urdf/arm.urdf"

    # See the cartesian_compliance_controller
    end_effector_link: "sixth_link"
    robot_base_link: "base_link"
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint

#    # See the cartesian_compliance_controller
    command_interfaces:
      - position
        #- velocity

    solver:
        error_scale: 1.0
        iterations: 10
        publish_state_feedback: True

    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}

motion_control_handle:
  ros__parameters:
    robot_description: "/home/bburns/ros2/install/zebra_zero/share/zebra_zero/urdf/arm.urdf"

    end_effector_link: "sixth_link"
    robot_base_link: "base_link"
    joints:
      - first_joint
      - second_joint
      - third_joint
      - fourth_joint
      - fifth_joint
      - sixth_joint

